/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'arusarka' at '4/30/16 11:25 AM' with Gradle 2.13
 *
 * @author arusarka, @date 4/30/16 11:25 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
